#!/bin/sh

# Cancel if no argument is provided
if [ $# -eq 0 ]; then
    cat << EOF
Usage: ${0##*/} [dual|monitor|laptop|mirror]
Arrange your screens.

  dual       Use the built-in monitor as well as the attached monitor
  dual-wide  Use the built-in monitor as well as the attached monitor, but with wide resolution
  monitor    Use only the attached monitor, disable built-in monitor
  laptop     Use only the built-in monitor, deattach from other screes
  mirror     Mirror the content of the laptop to the attached monitor

EOF
    exit 1
fi

# Define primary screen
primary="eDP-1"

# Recognize screens
screen=$(xrandr --current | grep " connected" | grep -v "$primary" | head -n1 | cut -d " " -f1)

# Exit if no external monitor is detected and required for mode
if [ -z "$screen" ] && [ "$1" != "laptop" ]; then
    echo "No external monitor detected!"
    exit 1
fi

echo "Primary: $primary"
echo "External: $screen"

# Dual mode
if [ "$1" = "dual" ]; then
  xrandr --output "$screen" --mode 1920x1080
  xrandr --output "$primary" --mode 3200x1800 --scale 1 --right-of "$screen"
  #xrandr --output "$primary" --auto --output "$screen" --auto --panning 3840x2160+3200+0 --scale 2x2 --right-of "$primary"
  #xrandr --output "$primary" --auto --output "$screen" --auto --panning 3840x2160+3200+0 --scale 2x2 --left-of "$primary"
fi
if [ "$1" = "dual-wide" ]; then
  xrandr --output "$screen" --mode 3840x1080
  xrandr --output "$primary" --mode 3200x1800 --scale 2 --right-of "$screen"
fi

# Monitor mode
if [ "$1" = "monitor" ]; then
  xrandr --dpi 96 --output "$screen" --auto --panning 0x0 --output "$primary" --off
fi

# Laptop mode
if [ "$1" = "laptop" ]; then
  xrandr --output "$screen" --off
fi

# Mirror mode
if [ "$1" = "mirror" ]; then
  #xrandr --output "$primary" --auto --output "$screen" --auto --panning 3840x2160+3200+0 --scale 2x2 --same-as "$primary"
  xrandr --output "$primary" --mode 3200x1800 
  xrandr --output "$screen" --mode 1920x1080 --scale 1.6
  #xrandr --dpi 96 --output "$primary" --auto --output "$screen" --auto --panning 0x0 --scale-from 3200x1800 --same-as "$primary"
fi

# Move workspaces based on mode
if [ "$1" = "dual" ] || [ "$1" = "dual-wide" ]; then
    # Move workspaces to external monitor
    for i in {2..9}; do
        i3-msg "workspace $i; move workspace to output $screen" > /dev/null
    done
fi


# Update background image:
# These are redundant as they are already in the i3 config file

# Fix background issues
#if [ -f ~/.fehbg ]; then
#    ~/.fehbg &
#else
#    feh --bg-scale /path/to/your/wallpaper.jpg &
#fi

# Restart compositor properly
#pkill picom
#sleep 1
#picom -b &

# Delay nitrogen execution to prevent X errors
#sleep 2
#nitrogen --restore &

# Restart i3
i3-msg restart > /dev/null
