#! /usr/bin/env python3

import os
from base64 import b64encode
import argparse, math
import binascii

''' Todo:
    - add options for different charsets
    - understand encodings
    - option to generate to clipboard (additionally)
    - option to generate may pws in one go
    - fix two equality signs at the end
'''

parser=argparse.ArgumentParser("Generate password based on /dev/urandom")
parser.add_argument('-l', '--length',  default=16, type=int, \
        help="password length, default: 16")
args = parser.parse_args()


numbytes = 3*math.floor(args.length/4)

key = os.urandom(numbytes)
text = b64encode(key).decode('utf-8')
print(text)
#print(len(text))

#key = os.urandom(numbytes)
#text = binascii.b2a_qp(key, istext=True).decode('UTF-8')
#text = b64encode(key).decode('ascii')
#print(text)
#print(len(text))

