#! /usr/bin/env python3

import argparse
import requests, io, base64
from PIL import Image

parser = argparse.ArgumentParser("convert textfile to mermaid chart")
parser.add_argument('input', help="file containing mermaid syntax")
parser.add_argument('-o', metavar='output', dest='output', \
        help="set output file name including suffix. default: inputfilename.jpg")
args = parser.parse_args()

f = open(args.input, 'r')
graph = f.read()

graphbytes = graph.encode("ascii")
base64_bytes = base64.b64encode(graphbytes)
base64_string = base64_bytes.decode("ascii")
img = Image.open(io.BytesIO(requests.get('https://mermaid.ink/img/' + base64_string).content))
if args.output is not None:
    img.save(args.output)
else:
    img.save("chart.jpg")
